"""many to many table

Revision ID: 418107c04c15
Revises: 59d529f3acec
Create Date: 2026-09-04 07:17:42.170801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '418107c04c15'
down_revision: Union[str, Sequence[str], None] = '59d529f3acec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests_purchases',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('purshase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purshase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', 'purshase_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests_purchases')
    # ### end Alembic commands ###
