"""add field with nullable  

Revision ID: 59d529f3acec
Revises: a587490b4dfb
Create Date: 2026-08-28 13:35:26.897645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d529f3acec'
down_revision: Union[str, Sequence[str], None] = 'a587490b4dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'active_message_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'active_message_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
