"""add field to users 

Revision ID: a587490b4dfb
Revises: e684b40f8122
Create Date: 2026-08-28 13:23:52.829827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a587490b4dfb'
down_revision: Union[str, Sequence[str], None] = 'e684b40f8122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'active_message_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'active_message_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
