"""new DB structure

Revision ID: bd2d19396f32
Revises: 418107c04c15
Create Date: 2026-09-04 16:12:03.780371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd2d19396f32'
down_revision: Union[str, Sequence[str], None] = '418107c04c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests_purchases')
    op.drop_table('purchases')
    op.add_column('requests', sa.Column('purchased_by_user_id', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('receipt_id', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('price', sa.Numeric(), nullable=True))
    op.add_column('requests', sa.Column('quantity', sa.Numeric(), nullable=True))
    op.add_column('requests', sa.Column('match_confidence', sa.Numeric(), nullable=True))
    op.create_foreign_key(None, 'requests', 'receipts', ['receipt_id'], ['id'])
    op.create_foreign_key(None, 'requests', 'users', ['purchased_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'match_confidence')
    op.drop_column('requests', 'quantity')
    op.drop_column('requests', 'price')
    op.drop_column('requests', 'receipt_id')
    op.drop_column('requests', 'purchased_by_user_id')
    op.create_table('purchases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('purchased_by_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('purchased_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('match_confidence', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['purchased_by_user_id'], ['users.id'], name=op.f('purchases_purchased_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], name=op.f('purchases_receipt_id_fkey')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('purchases_request_id_fkey')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('purchases_store_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('purchases_pkey'))
    )
    op.create_table('requests_purchases',
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purshase_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['purshase_id'], ['purchases.id'], name=op.f('requests_purchases_purshase_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('requests_purchases_request_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', 'purshase_id', name=op.f('requests_purchases_pkey'))
    )
    # ### end Alembic commands ###
