"""empty message

Revision ID: cda88350a75b
Revises: e2c3b6e15ab2
Create Date: 2026-09-07 14:52:42.128307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cda88350a75b'
down_revision: Union[str, Sequence[str], None] = 'e2c3b6e15ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('requests_purchased_by_user_id_fkey'), 'requests', type_='foreignkey')
    op.drop_column('requests', 'purchased_by_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('purchased_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('requests_purchased_by_user_id_fkey'), 'requests', 'users', ['purchased_by_user_id'], ['id'])
    # ### end Alembic commands ###
